### ISSUE TITLE
React Native TODO

### ISSUE THREAD

**Issue by satya164** [scrollback/io.scrollback.neighbor#1]
- [x] My localities page
- [x] Start discussion page
- [x] People list
- [x] Notification center
- [x] Chat input box
- [x] Write a share intent module
- [x] Get facebook and google login working
- [x] Implement push notification code
- [x] Handle heyneighbor.chat urls
- [x] Figure out file uploads
- [x] Use a mock store
- [x] Switch to proper store
- [x] Prevent reload on layout change
- [x] Implement signup flow
- [ ] Handle layout changes in components using `Dimensions`
- [ ] Show failure graphic when loading fails in embed.
- [ ] Handle errors
- [x] Don't add extra height for statusbar below Android 4.4
- [x] Show a failure message when socket connection failed
- [ ] Show failure message when sending text/thread fails
- [x] Show nearby rooms when related rooms are empty
- [ ] Bi-directional infinite scroll (?)
- [x] Switch to URL library
- [x] Log out option
- [x] Auto complete for user names
- [x] Auto capitalize for text inputs
- [x] Fix reply to and quote being added multiple times, should be simple as comparing with current props
- [x] In people list, add people from concerns which are not in related users
- [x] Add a spinner in splash screen
- [x] Remove text from Google login dialog
- [x] Save push notification preferences in device
- [x] Register for push notifications every 24 hours
- [x] Don't show push notifications in statusbar when app is open
- [x] Register for push notifications on sign up
- [x] Prompt for enabling GPS is not following any rooms
- [x] Wrap my accounts page is scrollview
- [ ] Animate out notifications
- [x] Auto follow rooms
- [x] Cancel upload on componentWillUnmount
- [x] Add height and width to Avatar style
- [x] Handle room doesn't exist / discussion doesn't exist
- [x] Integrate crashlytics and leakcanary
- [x] Keep data in sync when user comes back online after being offline

**Comment by chirag04** [comment]
@satya164 I saw facebook and google login implemented here. I think it's a good candidate to open source as a module. `react-native-social-login`?

I can help on ios side once the api is finalized

what do you think?

**Comment by satya164** [comment]
@chirag04 Yes. I want to open source it. Right now I was focusing on completing the app.

Any help will be appreciated. I can start working on it may be in a week. Thanks :D

**Comment by satya164** [comment]
BTW, if you've any suggestions on the API, please comment. We can publish a social login module together :D

**Comment by chirag04** [comment]
Cool. I will read your source code and see if i can come up with an api.

**Comment by satya164** [comment]
@chirag04 Awesome. Looking forward to it.
